name: Force update databases
run-name: Force update databases
on:
  workflow_dispatch:
jobs:
  force-update-db:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
      actions: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Remove existing CSVs & duckdb
        env:
            github_token: ${{ secrets.GH_TOKEN }}
            branch: main   
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git rm -r --cached ./csv || true
          git rm -r --cached ffxiv_price.duckdb || true
          git commit -m "Remove existing CSVs & duckdb" || true
          git push
      - name: Download CSVs again
        env:
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh workflow run main.yml --ref main
          
